version: "3.9"

services:

  monitoring:
    container_name: adr_monitoring
    build:
      context: Monitoring
      dockerfile: Dockerfile
    volumes:
      - ./Monitoring:/project
#    tty : true
    environment:
      TZ: Asia/Seoul
      ADR_DB: openadr
      ADR_USER: user
      ADR_PASSWORD: 1234
      ADR_HOST: db
      ADR_PORT: 5432 # 외부 노출 포트 말고 내부 포트를 기입
      TEST_HOST: db_test
      TEST_PORT: 5432
